// /**
//  * Code is auto-generated by Application Logic, DO NOT EDIT.
//  * @version(2.0)
//  */
// const LCAPApplicationService = require('@sap/low-code-event-handler');
// const importcsv_Logic = require('./code/importcsv-logic');

// class ImportService extends LCAPApplicationService {
//     async init() {

//         this.on('importCSV', async (request) => {
//             return importcsv_Logic(request);
//         });

//         return super.init();
//     }
// }


// module.exports = {
//     ImportService
// };

const cds = require("@sap/cds");
const { parse } = require("csv-parse/sync");

module.exports = cds.service.impl(function () {
  this.on("importCSV", async (req) => {
    const csvText = req.data?.csv;
    if (!csvText || typeof csvText !== "string") {
      return req.reject(400, "No CSV data provided.");
    }

    let rows;
    try {
      rows = parse(csvText, {
        columns: true,
        skip_empty_lines: true,
        trim: true,
        bom: true
      });
    } catch (e) {
      return req.reject(400, `CSV parse error: ${e.message}`);
    }

    if (!rows.length) return "CSV is empty.";

    // ✅ Get DB entity (not service projection)
    const db = cds.entities("sap.capire.incidents");
    const Incidents = db?.Incidents;

    if (!Incidents) {
      return req.reject(500, "DB entity sap.capire.incidents.Incidents not found. Check db/schema.cds namespace.");
    }

    const norm = (v) =>
      String(v ?? "")
        .trim()
        .toLowerCase();

    const mapUrgency = (v) => {
      const x = norm(v);
      if (!x) return "M";
      if (x === "h" || x === "high") return "H";
      if (x === "m" || x === "medium") return "M";
      if (x === "l" || x === "low") return "L";
      // allow already-coded values
      const up = String(v).trim().toUpperCase();
      return ["H", "M", "L"].includes(up) ? up : "M";
    };

    const mapStatus = (v) => {
      const x = norm(v).replace(/\s+/g, "_"); // "in process" -> "in_process"
      if (!x) return "N";
      const m = {
        new: "N",
        assigned: "A",
        in_process: "I",
        on_hold: "H",
        resolved: "R",
        closed: "C"
      };
      if (m[x]) return m[x];
      const up = String(v).trim().toUpperCase();
      return ["N", "A", "I", "H", "R", "C"].includes(up) ? up : "N";
    };

    const tx = cds.tx(req);

    let inserted = 0;
    const errors = [];

    for (let i = 0; i < rows.length; i++) {
      const rowNo = i + 2; // header is line 1
      const r = rows[i];

      // Your CSV: title,customerId,urgency_code,status_code
      const title = String(r.title || "").trim();
      const customerId = String(r.customerId || r.customer_ID || r.customerID || "").trim();

      if (!title) { errors.push(`Row ${rowNo}: missing title`); continue; }
      if (!customerId) { errors.push(`Row ${rowNo}: missing customerId`); continue; }

      const urgency_code = mapUrgency(r.urgency_code);
      const status_code = mapStatus(r.status_code);

      try {
        await tx.run(
          INSERT.into(Incidents).entries({
            title,
            customer_ID: customerId,
            urgency_code,
            status_code
          })
        );
        inserted++;
      } catch (e) {
        // If customerId does not exist and FK is enforced, you’ll see the error here
        errors.push(`Row ${rowNo}: insert failed (${e.message})`);
      }
    }

    const skipped = errors.length;
    return skipped
      ? `Imported ${inserted}. Skipped ${skipped}.\nFirst errors:\n- ${errors.slice(0, 10).join("\n- ")}`
      : `Imported ${inserted} incidents successfully.`;
  });
});
